export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Tomate redondo',
        description: 'Recomendado para comida rapida',
        weight: '1/2 kg',
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: 'Tomate perita',
        description: 'Ideal para ensaladas',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: 'Lechuga mantecosa',
        description: 'Rica lechuga',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: 'Lechuga criolla',
        description: 'Ideal para todo',
        weight: '1/3 kg',
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: 'Cebolla Blanca',
        description: 'Cebolla de muy buena calidad',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: 'Cebolla morada',
        description: 'Ideal para no llorar',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: 'Papas blancas',
        description: 'Ideal para esas comidas que mas gustan',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: 'Papas negras',
        description: 'Estilo muy natural',
        weight: '1/3 kg',
        price: 20,
    },
]